// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { registerEmbedCard } from "embed-card/web-component"

registerEmbedCard()
</script>

<template>
  <main class="demo">
    <p class="eyebrow">embed-card · Vite + Vue</p>
    <h1>Turn a URL into a rich embed</h1>
    <p class="lede">
      Vue uses the custom element from <code>embed-card/web-component</code>.
      Call <code>registerEmbedCard()</code> once, then use
      <code>&lt;embed-card&gt;</code> in your template.
    </p>
    <embed-card
      url="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      accent-color="#e11d48"
      border-color="rgba(225,29,72,0.18)"
      radius="28px"
      shadow="0 28px 100px rgba(225,29,72,0.14)"
    />
  </main>
</template>

// examples/next-app/app/page.tsx
"use client"

import { EmbedCard } from "embed-card"

const DEMO_URL =
  "https://www.youtube.com/watch?v=dQw4w9WgXcQ" as const

const DEMO_THEME = {
  accentColor: "#e11d48",
  borderColor: "rgba(225,29,72,0.18)",
  radius: 28,
  shadow: "0 28px 100px rgba(225,29,72,0.14)",
} as const

export default function Page() {
  return (
    <main
      style={{
        margin: "0 auto",
        maxWidth: "56rem",
        padding: "2.5rem 1.5rem 4rem",
      }}
    >
      <p
        style={{
          margin: 0,
          fontSize: "0.75rem",
          fontWeight: 600,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "#64748b",
        }}
      >
        embed-card · Next.js (App Router)
      </p>
      <h1
        style={{
          margin: "0.75rem 0 0",
          fontSize: "1.75rem",
          fontWeight: 600,
          letterSpacing: "-0.03em",
        }}
      >
        Turn a URL into a rich embed
      </h1>
      <p style={{ margin: "0.75rem 0 1.75rem", color: "#475569" }}>
        This page imports <code>EmbedCard</code> from{" "}
        <code>embed-card</code>. Swap <code>DEMO_URL</code> for your own link.
      </p>
      <EmbedCard theme={DEMO_THEME} url={DEMO_URL} />
    </main>
  )
}
